### PR TITLE
implemented interface methods, modified properties.

### LINKED ISSUE #7: add properties
setup the properties for the linked list class that was inherited mentioned in #6 and initialise where appropriated

### LINKED ISSUE #8: implement the interface methods
When each task is completed, tick it here.
- [ ] implement the remove method @de-lia @Dezzy237 
- [ ] implment the addFirst method @Ngumbutlar Josue
- [ ] implement the addLast method @mofirojean @shenyuygoodness 
- [ ] implement the other helper methods

### PR DESCRIPTION
**Pull request by de-lia**
fixes #7 
set up properties for the linked list class. Modified the size property.

fixes #8 
implemented the interface methods:
- remove method of @Dezzy237 and @de-lia. We had to change remove() to removeFirst() to explain that removal only occurs at the head except otherwise.
- addFirst method of @Ngumbutlar and @Signeemmanuel 
- addLast method of @mofirojean and @shenyuygoodness 
- and the other helper methods.

### CODE REVIEW

**Comment by elroykanye** [comment]
This is not what I wanted 😄

**Comment by elroykanye** [comment]
Close this PR and do what I asked.

**Comment by de-lia** [comment]
> Close this PR and do what I asked.

Should I delete the branch too?

**Comment by elroykanye** [comment]
Yes

**Comment by de-lia** [comment]
> Yes

Okay.

**Pull request closed without merging**
