### PR TITLE
LinkedList class, implementing the interface

### LINKED ISSUE #6: add a base LinkedListImpl class
add a base class that implements the interface you created and while overriding the methods inherited

### PR DESCRIPTION
**Pull request by nebadesmondc**
fixes #6 
created a class called LinkedListImpl that implements the interface created

### CODE REVIEW

**Comment by elroykanye** [comment]
change the name of this pr. put an appropriate name.

**Comment by elroykanye** [comment]
you did not put "fixes #{issue}" in your comment

**Comment by nebadesmondc** [comment]
> you did not put "fixes #{issue}" in your comment

i did ..from intellij, check up

**Comment by nebadesmondc** [comment]
> change the name of this pr. put an appropriate name.

what should i put?

**Comment by elroykanye** [comment]
> > change the name of this pr. put an appropriate name.
> 
> what should i put?

You did it just after I said it dude. It is showing there that you edited the comment.

**Comment by elroykanye** [comment]
> > change the name of this pr. put an appropriate name.
> 
> what should i put?

Something appropriate

**Comment by elroykanye** [comment]
Don't close a PR without my consent.

**Comment by nebadesmondc** [comment]
Sorry I thought you said I should redo itSent from my Galaxy smartphone.
-------- Original message --------From: Elroy Kanye ***@***.***> Date: 4/4/22  3:07 PM  (GMT+01:00) To: Kanyelings/linked_list ***@***.***> Cc: Neba Desmond ***@***.***>, State change ***@***.***> Subject: Re: [Kanyelings/linked_list] fixes #6 (PR #22) 
Don't close a PR without my consent.

**Comment by elroykanye** [comment]
I said rename, not redo.

**Comment by nebadesmondc** [comment]
> I said rename, not redo.
please how do i rename?

**Review by elroykanye — APPROVED** [review]

**Pull request merged**
