### PR TITLE
created interface for the linked list.

### LINKED ISSUE #9: add an interface for the LinkedList
I deleted the initial code that was here.
Create a new interface and name it ILinkedList, populate it with all the methods you agreed on.
Open a unique PR for that.

### PR DESCRIPTION
**Pull request by nebadesmondc**
fixes #9  

added the necessary methods needed to create the linked list class

### CODE REVIEW

**Comment by Dezzy237** [comment]
#13

**Comment by elroykanye** [comment]
> #13

This is not how it is supposed to be.
You are supposed to write "fixes #{issue number}"
GitHub will automatically understand from the word fixes.

You can edit the comment

**Comment by Dezzy237** [comment]
fixes #13

**Comment by elroykanye** [comment]
> fixes #13

No. Edit the first comment on this thread

> added the necessary methods needed to create the linked list class

This one

**Review by elroykanye — APPROVED** [review]
Consider making sure that next time, your code has comments.

**Comment by nebadesmondc** [comment]
yes i will

**Comment by elroykanye** [comment]
Secondly, the number you put (13) was wrong.
You had to put the ISSUE NUMBER, not pull request number. I have fixed that.

**Comment by elroykanye** [comment]
Anyway, good job on first trial @Dezzy237

**Pull request merged**
