### PR TITLE
Discarded the idea of using npm for the tasks

### LINKED ISSUE #20: Mentioning npm when it's not in use
I don't think mentioning npm is necessary especially as we are not using it.

Screenshot_20220404-130950

### PR DESCRIPTION
**Pull request by kimbifavour**
fixes #20

Made some changes to the readme file. Since in this project no npms were used, I edited the line that mentions it all together.

### CODE REVIEW

**Comment by elroykanye** [comment]
You have not mentioned which issue this pr closes

**Review by elroykanye — APPROVED** [review]

**Comment by elroykanye** [comment]
You have not provided an explanatory comment for this pr

**Comment by elroykanye** [comment]
Check how this was done: #11

**Comment by elroykanye** [comment]
I did not ask you to close the PR

**Comment by elroykanye** [comment]
Neither did I ask you to delete the branch. You have to ask for confirmation to do this.

**Comment by kimbifavour** [comment]
I'm sorry. I wanted to redo it since github didn't approve of the PR
somehow, and the changes were not merged

**Comment by elroykanye** [comment]
I am the one who did not approve. Contact me on whatsapp.

**Comment by elroykanye** [comment]
Are you still working on this?

**Pull request merged**
