### PR TITLE
modified interface.

### LINKED ISSUE #19: Misplaced Interface
The ILinkedList interface has been created outside of the com/kanyelings package

### PR DESCRIPTION
**Pull request by de-lia**
fixes #19 

puts the interface in its required location, in the kanyelings' package.

### CODE REVIEW

**Review by elroykanye — CHANGES_REQUESTED** [review]
I only see that you have added 1 whitespace line. I don't think you have actually moved the file itself.

Do the task correctly, make another commit and push to this same branch.

**Comment by de-lia** [comment]
Done.

**Review by elroykanye — APPROVED** [review]
Looks good

**Comment by de-lia** [comment]
Thank you.

**Pull request merged**
